update project to Swift 3
STAR-ZERO/STZPopupView pull request #6
Opened 2016-09-08 14:35 UTC by chrisdoc

This PR updates STZPopupView to use Swift 3

2016-09-20 14:06 UTC, STAR-ZERO commented on Source/UIViewController+STZPopupView.swift
> +    fileprivate func completionShowAnimation(_ finished: Bool) {
I prefer not to use underscore.
`private func completionShowAnimation(finished: Bool)`

2016-09-20 14:06 UTC, STAR-ZERO commented on Source/UIViewController+STZPopupView.swift
> +    fileprivate func completionDismissAnimation(_ finished: Bool) {
I prefer not to use underscore.
`private func completionDismissAnimation(finished: Bool)`

2016-09-20 14:17 UTC, STAR-ZERO commented on Source/UIViewController+STZPopupView.swift
> +    public func presentPopupView(_ popupView: UIView, config: STZPopupViewConfig = STZPopupViewConfig()) {
I prefer not to use underscore. 
`public func present(popupView: UIView, config: STZPopupViewConfig = STZPopupViewConfig())`

See https://developer.apple.com/reference/uikit/uiviewcontroller/1621380-present

API interface will change. It cannot be helped...

2016-09-20 14:19 UTC, STAR-ZERO requested changes
Thank you for PR.

There are several request changes.

2016-09-20 14:19 UTC, STAR-ZERO commented on Example/ViewController.swift
> +        button.addTarget(self, action: #selector(ViewController.touchClose), for: UIControlEvents.touchUpInside)
I prefer `#selector(touchClose)` to `#selector(ViewController.touchClose)`.

2016-09-20 14:19 UTC, STAR-ZERO commented on Source/UIViewController+STZPopupView.swift
> +    fileprivate var targetView: UIView {
In this case, `private` is better than `fileprivate`.

2016-09-20 14:19 UTC, STAR-ZERO commented on Source/UIViewController+STZPopupView.swift
> +            dismissButton.addTarget(self, action: #selector(UIViewController.dismissPopupView), for: UIControlEvents.touchUpInside)
I prefer `#selector(dismissPopupView)` to `#selector(UIViewController.dismissPopupView)`.

2016-09-21 14:17 UTC, chrisdoc commented
@STAR-ZERO thanks for the review, i fixed your remarks

2016-09-22 23:38 UTC, STAR-ZERO commented
I'm sorry, I didn't explain it clearly enough.

* Please change all `fileprivate` to `private` in `Source/UIViewController+STZPopupView.swift`

I'm sorry, come to think of it, your first PR code is correct.

* Please use underscore at https://github.com/STAR-ZERO/STZPopupView/pull/6/commits/74187f24863f176802f55e0280a55105665c23ef#diff-a95f0f383b64e6ebc7aa159259f33594R70
  * before: `presentPopupView(popupView: UIView, config: STZPopupViewConfig = STZPopupViewConfig())`
  * after: `presentPopupView(_ popupView: UIView, config: STZPopupViewConfig = STZPopupViewConfig())`

Thanks:bow:

2016-09-23 05:56 UTC, chrisdoc commented
@STAR-ZERO  no problem, I amended my `_` changes and replaced `fileprivate` with `private`

2016-09-23 14:37 UTC, STAR-ZERO approved these changes

2016-09-23 14:38 UTC, merged

2016-09-23 14:39 UTC, STAR-ZERO commented
Thanks :smile::thumbsup: